### ISSUE TITLE
I cant register in ur web

### ISSUE THREAD

**Issue by alex2k17** [JR-UE4/EpicLeaderboard#9]
I have tried to register on your website but the confirmation email never arrived. I've tried another email account and it didn't work either.

**Comment by jahaniam** [comment]
Same, tried with two emails and checked for spam. It doesn't work

**Comment by jahaniam** [comment]
Nevermind, I just got the email. It will take ~5-10 mins.

**Comment by alex2k17** [comment]
Done!
